# Murano Product Spec File, Machine Control Demo


resources:
-   alias: temperature
    format: float
-   alias: state
    format: string
-   alias: uptime
    format: integer
-   alias: tempset
    format: float
-   alias: control
    format: integer
    initial: 0
-   alias: cloudtempset
    format: float
-   alias: cloudcontrol
    format: integer
    initial: 0
-   alias: uptime
    format: integer
